import os
import glob
import json

def export_all_to_md():
    output_file = "all_tuned_results_full_dump.md"
    base_path = os.path.join("results", "tuned_results")
    
    if not os.path.exists(base_path):
        print(f"Error: '{base_path}' not found. Keep this script in your project root!")
        return
        
    data_dict = {}
    
    # We iterate over the exact folder names created by your training script
    for model_folder in ["efficientnet", "cnn"]:
        for method_folder in ["ours", "nctd"]:
            
            metrics_dir = os.path.join(base_path, model_folder, method_folder, "metrics")
            if not os.path.exists(metrics_dir):
                continue
                
            for metrics_fpath in glob.glob(os.path.join(metrics_dir, "*_metrics.json")):
                filename = os.path.basename(metrics_fpath)
                
                # Strip the prefix generated by save_stem = f"{method_name}_{model_type}_{ds_stem}"
                ds_name = filename.replace("_metrics.json", "")
                prefixes = [
                    "NCTD_efficientnet_", "ours_efficientnet_",
                    "NCTD_nctd_cnn_", "ours_nctd_cnn_"
                ]
                for p in prefixes:
                    if ds_name.startswith(p):
                        ds_name = ds_name[len(p):]
                        break
                
                hp_fpath = os.path.join(metrics_dir, filename.replace("_metrics.json", "_hyperparams.json"))
                combo_name = f"{'EfficientNet' if model_folder == 'efficientnet' else 'CNN'} + {'Ours' if method_folder == 'ours' else 'NCTD'}"
                
                if ds_name not in data_dict:
                    data_dict[ds_name] = {}
                    
                data_dict[ds_name][combo_name] = {"metrics": None, "hyperparams": None}
                
                # Dump the exact entire JSON object into memory
                try:
                    with open(metrics_fpath, 'r', encoding='utf-8') as f:
                        data_dict[ds_name][combo_name]["metrics"] = json.load(f)
                except Exception as e:
                    print(f"Error reading metrics for {ds_name}: {e}")
                    
                try:
                    if os.path.exists(hp_fpath):
                        with open(hp_fpath, 'r', encoding='utf-8') as f:
                            data_dict[ds_name][combo_name]["hyperparams"] = json.load(f)
                except Exception as e:
                    print(f"Error reading hyperparams for {ds_name}: {e}")
                    
    if not data_dict:
        print("No metrics found in 'results/tuned_results'. Check if the folder is empty.")
        return
        
    # Write everything faithfully to a Markdown file
    with open(output_file, 'w', encoding='utf-8') as md:
        md.write("# Complete Tuned Results and Hyperparameters Dump\n\n")
        
        for ds in sorted(data_dict.keys()):
            md.write(f"## Dataset: `{ds}`\n\n")
            
            for combo in sorted(data_dict[ds].keys()):
                md.write(f"### {combo}\n\n")
                
                md.write("**Hyperparameters:**\n")
                md.write("```json\n")
                hp = data_dict[ds][combo]["hyperparams"]
                if hp:
                    md.write(json.dumps(hp, indent=2) + "\n")
                else:
                    md.write("{}\n")
                md.write("```\n\n")
                
                md.write("**Metrics:**\n")
                md.write("```json\n")
                metrics = data_dict[ds][combo]["metrics"]
                if metrics:
                    md.write(json.dumps(metrics, indent=2) + "\n")
                else:
                    md.write("{}\n")
                md.write("```\n\n")
                
            md.write("---\n\n")
            
    print(f"Exported complete JSON dump for {len(data_dict)} datasets to '{output_file}'.")

if __name__ == "__main__":
    export_all_to_md()
